### ISSUE TITLE
1.1.1版本出现报错问题

### ISSUE THREAD

**Issue by 996157497** [1n7erface/RequestTemplate#23]
1.使用i参数 扫描整个C段 识别某种资产时可能会出现以下报错情况。
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/45760229/217685351-109f0679-05af-4331-ba30-07b0666b46ab.png">
以下为报错内容：
```
panic: runtime error: slice bounds out of range [64:35]

goroutine 167 [running]:
github.com/hirochachacha/go-smb2/internal/smb2.PacketCodec.Data(...)
        github.com/hirochachacha/go-smb2@v1.1.0/internal/smb2/packet.go:208
github.com/hirochachacha/go-smb2.accept(0xa680?, {0xc0007701b0, 0xc000ca9100, 0xc0017f3e60})
        github.com/hirochachacha/go-smb2@v1.1.0/conn.go:641 +0x418
github.com/hirochachacha/go-smb2.(*Negotiator).negotiate(0xc0000edd4a, {0x1a820f0?, 0xc0012a2600}, 0xc0012a25e8, {0x1a81c58, 0xc000120000})
        github.com/hirochachacha/go-smb2@v1.1.0/conn.go:122 +0x354
github.com/hirochachacha/go-smb2.(*Dialer).DialContext(0xc0000edd48, {0x1a81c58, 0xc000120000}, {0x1a85b20, 0xc00135a030})
        github.com/hirochachacha/go-smb2@v1.1.0/client.go:62 +0x199
github.com/hirochachacha/go-smb2.(*Dialer).Dial(...)
        github.com/hirochachacha/go-smb2@v1.1.0/client.go:34
RequestTemplate/Tools.bruteSMB({{{0xc000034970, 0xd}, 0x1bd, {0x18fc412, 0x3}}, {0x190239e, 0xd}, {0x18fd5f7, 0x6}})
        RequestTemplate/Tools/SMBTemplate.go:50 +0x25d
RequestTemplate/Tools.SMBWorker(0x0?)
        RequestTemplate/Tools/SMBTemplate.go:20 +0x1e9
created by RequestTemplate/Tools.InitSMB
        RequestTemplate/Tools/BruteTemplate.go:82 +0x1d
```

2.使用-i时 例如：1.1.1.1/24可以扫描整个网段，但是1.1.1.1-100则不会出现数据

图1为正常1.1.1.1/24
![2](https://user-images.githubusercontent.com/45760229/217685019-5adb78db-dff0-4f1a-b128-5910d3cdcf48.png)
图2为1.1.1.1-100则不会出现数据

![3](https://user-images.githubusercontent.com/45760229/217685201-5a921bc2-1569-463d-93f9-a9deab4ba17f.png)

**Comment by 1n7erface** [comment]
已解决，过段时间更新版本。
